http:
  hostname: localhost
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  order:
    host: localhost
    paths: ['/api/orders','/api/orders/*']
  product:
    host: localhost
    paths: ['/api/products',,'/api/products/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  orderService:
    url: 'http://localhost:7778'
  productService:
    url: 'http://localhost:7777'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              ignorePath: false
              prependPath: true
              stripPath: true
              changeOrigin: true
  prouctPipeline:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
              ignorePath: false
              prependPath: true
              stripPath: true
              changeOrigin: true
